{
 "title": "Coffee Demo",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Last Recorded Reading",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "query": "SELECT (ABS(mean(\"pin_voltage\") / 3.3) * 100) as amperage  FROM \"power_meter\" WHERE $timeFilter GROUP BY time(5s) fill(previous)",
     "select": [
      [
       { "params": [ "adc_value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ADC Value",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "adc_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pin Voltage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "select": [
      [
       { "params": [ "pin_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Amperage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "power_meter",
     "query": "SELECT (ABS(mean(\"pin_voltage\") / 3.3) * 100) as amperage  FROM \"power_meter\" WHERE $timeFilter GROUP BY time(5s) fill(previous)",
     "select": [
      [
       { "params": [ "adc_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Brewing Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "queryText": "SELECT \n  t._time, \n  CASE\n    WHEN t.amperage >= 0.02 THEN 'brewing'\n    ELSE 'standby'\n  END as state\nFROM (\n  SELECT\n    DATE_BIN(INTERVAL '5 seconds', time, TIMESTAMP '2022-01-01 00:00:00Z') AS _time,\n    (ABS(avg(\"pin_voltage\") / 3.3) * 100) as amperage \n  FROM \"power_meter\"\n  WHERE $__timeRange(time)\n  GROUP BY _time\n) as t\nORDER BY t._time"
    }
   ]
  }
 ]
}